# Generated by Django 4.1.7 on 2023-04-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0002_rename_user_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRecord",
            new_name="PatientRecord",
        ),
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="Patients",
        ),
    ]
