# Generated by Django 4.1.7 on 2023-04-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_userrecord_patientrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("practitioner_id", models.CharField(max_length=150, unique=True)),
                (
                    "patients",
                    models.ManyToManyField(
                        related_name="practitioner_patients", to="api.patients"
                    ),
                ),
            ],
        ),
    ]
