# Generated by Django 4.1.7 on 2023-04-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_practitioner_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practitioner",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$ADgf8BIUYYn8uCR9ViKyxt$8ZOrhU9A8a+yHBBbvxfz6kMT0xw1gkH46MZ/YYaWYd4=",
                help_text="Required. Must be set.",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
