# Generated by Django 4.1.7 on 2023-04-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_practitioner_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practitioner",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$4BZBC3bxMXbq3AJZao0aoy$A0YVsGOOHWmPBk0a3cTUk4bECxjLr5oELMGQhPFs16U=",
                help_text="Required. Must be set.",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
