# Generated by Django 4.1.7 on 2023-04-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_practitioner_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practitioner",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$qzbCnTwnbEtfn4KuKWKMgI$pYSzVn8QMPcUXds/yroZyi5MzGxJJAXqmX4zOPxhrHQ=",
                help_text="Required. Must be set.",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
