# Generated by Django 4.1.7 on 2023-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_practitioner_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practitioner",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$hG7q5CE2Ehyq6mxVREioSn$CYdMEOcohFfKOB8G/1mJDLMwDIxGjqRNun2IgLjlgwg=",
                help_text="Required. Must be set.",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
