# Generated by Django 4.1.7 on 2023-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_practitioner_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patients",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.AlterModelOptions(
            name="practitioner",
            options={
                "verbose_name": "Practitioner",
                "verbose_name_plural": "Practitioners",
            },
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$Q2TQILdHvUOpJEpD8kX1gH$mvsAcG9ERcvkNmW4XHn+iXRr2NsXXiKtj8iDwPs9EQ0=",
                help_text="Required. Must be set.",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
